### PR TITLE
Closes #5 - Add Python 3 support

### LINKED ISSUE #5: Add python3 support
cf https://github.com/novafloss/django-compose-settings/blob/master/circle.yml#L3

### PR DESCRIPTION
**Pull request by vrialland**

### CODE REVIEW

**Comment by vrialland** [comment]
ping @toopy as I can't ask for reviewers :)

**Review by tbcvl — APPROVED** [review]
LGTM but @toopy is more important :)

**Review by toopy — APPROVED** [review]

**Comment by vrialland** [comment]
@toopy I don't have the rights to merge it, could you please do it and prepare a release?

**Comment by vrialland** [comment]
ping @zebuline for follow-up as you created the original ticket

**Review by zebuline — APPROVED** [review]
thanks :)

**Pull request merged**
